audio:
  or_sample_rate: 16000
  sample_rate: 16000
#  sample_rate: 22050
  max_wav_value: 32768.0
  win_len: 256
  max_len: 176000
  data_percentage: 1.0
  audio_delay: 2.05


#mel:
#  n_fft: 1024
#  hop_length: 256
#  win_length: 1024

mel:
  n_fft: 320
  hop_length: 160
  win_length: 320