dataset: "librispeech"


adv: True


path:
  raw_path: "/storage/seit-guohanqi/librispeech_dataset/LibriSpeech_wav"
#  raw_path: "/home/yizhu/Data/LibriSpeech_wav"
  raw_path_test: "experiments/cloned_speechs"
  wm_speech: "./results/wm_speech"
  ckpt: "results/ckpt/"
  log_path: "results/log/"


watermark:
  length: 10
  future_amt: 51
  future_amt_waveform: 8000


optimize:
  lr: 0.00002
  lambda_e: 1.
  lambda_m: 10.
  # lambda_m: 0.01
  lambda_no_m: 0.01
  lambda_a: 0.01
  batch_size: 4  # remote batch_size=4, local batch_size=2
  step_size: 5000 # large value means do not decay
  gamma: 0.98
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  up_step: 4000
  anneal_steps: [300000, 400000, 500000]
  anneal_rate: 0.3
  lr_disc: 0.00002
  alpha: 10
  train_size: 31000


iter:
  epoch: 5
  # epoch: 100
  save_circle: 5
  show_circle: 100
  val_circle: 100
  data_divider: 5
  test_record_num: 100

wandb:
  enabled: false  # Set to true to enable wandb logging
  project: "real-time-voice-watermark"
  name: "shift 1"
  key: "9a11e5364efe3bb8fedb3741188ee0d714e942e2"
  WANDB_DIR: "/storage/seit-guohanqi/yizhu_wen/Real-time-Voice-Watermark/wandb_dir"
  WANDB_TMP_DIR: "/storage/seit-guohanqi/yizhu_wen/Real-time-Voice-Watermark/wandb_tmp_dir"